# Generated by Django 2.2.1 on 2019-06-15 20:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('detail', models.TextField(default='')),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('username', models.CharField(max_length=256)),
            ],
        ),
    ]
